<?php

	use App\Http\Controllers\Api\ActionItemController;
	use App\Http\Controllers\Auth\LoginController;
	use App\Http\Controllers\Auth\RegisterController;
	use App\Http\Controllers\ChatController;
	use App\Http\Controllers\ProfileController;
	use Illuminate\Support\Facades\Route;
	use App\Http\Controllers\AppController;


	// --- Authentication Routes (Generated by ui bootstrap --auth, modified) ---

// Login Routes
	Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
	Route::post('login', [LoginController::class, 'login']);
	Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes
	Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
	Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes (DISABLED) - Commented out or removed
// Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
// Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
// Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
// Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

// Email Verification Routes (DISABLED - primarily by removing MustVerifyEmail from User model)
// Route::get('email/verify', [VerificationController::class, 'show'])->name('verification.notice');
// Route::get('email/verify/{id}/{hash}', [VerificationController::class, 'verify'])->name('verification.verify');
// Route::post('email/resend', [VerificationController::class, 'resend'])->name('verification.resend');

// --- End Authentication Routes ---


	Route::get('/', [AppController::class, 'index'])->name('dashboard');
	Route::get('/home', [AppController::class, 'index'])->name('home');

	// --- Profile Route (Needs Controller and View) ---
	Route::middleware('auth')->group(function () {
		Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
		Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update'); // For handling form submission

		// Chat Routes
		Route::get('/chat/{chatHeaderId?}', [ChatController::class, 'show'])
		->where('chatHeaderId', '[0-9]+')
		->name('chat.show');

		// API Routes (Prefixed with /api and protected by auth)
		Route::prefix('api')->name('api.')->group(function () {
			Route::post('/chat', [ChatController::class, 'store'])->name('chat.store');
			// Use DELETE method for deleting resources
			Route::delete('/chat/messages/{userMessage}', [ChatController::class, 'destroyMessagePair'])
				->where('userMessage', '[0-9]+') // Ensure message ID is numeric
				->name('chat.messages.destroy');

			Route::delete('/chat/headers/{chatHeader}', [ChatController::class, 'destroyHeader'])
				->where('chatHeader', '[0-9]+') // Ensure header ID is numeric
				->name('chat.headers.destroy');

			Route::post('/chat/tts', [ChatController::class, 'textToSpeech'])->name('chat.tts');



			Route::get('/action-items', [ActionItemController::class, 'index'])->name('action-items.index');
			Route::post('/action-items', [ActionItemController::class, 'store'])->name('action-items.store');
			Route::patch('/action-items/{actionItem}', [ActionItemController::class, 'update'])
				->where('actionItem', '[0-9]+')
				->name('action-items.update'); // Use PATCH for partial updates
			Route::delete('/action-items/{actionItem}', [ActionItemController::class, 'destroy'])
				->where('actionItem', '[0-9]+')
				->name('action-items.destroy');


			//     Route::get('/meetings/{meetingId}', [AppController::class, 'getMeetingDetails']);
			//     Route::get('/notes/{noteId}', [AppController::class, 'getNoteDetails']);
			//     Route::get('/files/{fileId}', [AppController::class, 'getFileDetails']);
			//     Route::get('/recordings/{recordingId}', [AppController::class, 'getRecordingDetails']);
			//     Route::post('/settings', [AppController::class, 'updateSettings']);
			//     Route::post('/summarize', [AppController::class, 'summarize']);
			//     Route::post('/transcribe', [AppController::class, 'transcribe']);
		});

	});


	//	Auth::routes();
